import type React from "react"
import type { RoadmapItem } from "~/types/commonType"
import { ArrowLeft } from "lucide-react"

interface RoadmapDetailProps {
  item: RoadmapItem
  onBack: () => void
}

const RoadmapDetail: React.FC<RoadmapDetailProps> = ({ item, onBack }) => {
  return (
    <div className="p-6">
      <button onClick={onBack} className="mb-4 flex items-center text-blue-500 hover:text-blue-600">
        <ArrowLeft size={20} className="mr-2" />
        Back to Roadmap
      </button>
      <h2 className="text-2xl font-bold mb-4">{item.title}</h2>
      <p className="mb-4">
        This is a detailed explanation of {item.title}. In a real application, this would be generated by an AI based on
        the topic.
      </p>
      {item.children.length > 0 && (
        <div>
          <h3 className="text-xl font-semibold mb-2">Subtopics:</h3>
          <ul className="list-disc pl-5">
            {item.children.map((child) => (
              <li key={child.id}>{child.title}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

export default RoadmapDetail

